  CREATE TABLE "C##NATL_HEALTH"."PROCESSING_YEAR_CODE" 
   (	"PROCESSING_YEAR_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCESSING_YEAR_CODE_SHORT_DSC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCESSING_YEAR_CODE_LONG_DSC" VARCHAR2(20 BYTE), 
	"PROCESSING_YEAR_CODE_REFERNCE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PROCESSING_YEAR_CODE_PK" PRIMARY KEY ("PROCESSING_YEAR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS";