
  CREATE TABLE "C##NATL_HEALTH"."RECORD_TYPE_CODE" 
   (	"RECORD_TYPE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RECORD_TYPE_CODE_SHORT_DESC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"RECORD_TYPE_CODE_LONG_DESC" VARCHAR2(20 BYTE), 
	"RECORD_TYPE_CODE_REFERENCE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "RECORD_TYPE_CODE_PK" PRIMARY KEY ("RECORD_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;