
  CREATE TABLE "C##NATL_HEALTH"."PROCESSING_QUARTER_CODE" 
   (	"PROCESSING_QUARTER_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCESSING_QUARTR_CDE_SHRT_DEC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROCESSING_QUARTER_CDE_LNG_DSC" VARCHAR2(20 BYTE), 
	"PROCESSING_QUARTER_CODE_RFRNCE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "PROCESSING_QUARTER_CODE_PK" PRIMARY KEY ("PROCESSING_QUARTER_CODE")
   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;