OPTIONS (SKIP=1)
LOAD DATA
INFILE PROCESSING_YEAR_CODE_data.csv
BADFILE PROCESSING_YEAR_CODE_data.bad
DISCARDFILE PROCESSING_YEAR_CODE_data.dsc
INSERT INTO TABLE PROCESSING_YEAR_CODE
FIELDS TERMINATED BY ","
(PROCESSING_YEAR_CODE, PROCESSING_YEAR_CODE_SHORT_DSC, PROCESSING_YEAR_CODE_LONG_DSC, PROCESSING_YEAR_CODE_REFERNCE)