
  CREATE TABLE "C##NATL_HEALTH"."x" 
   (	"x_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"x_CODE_SHORT_DESC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"x_CODE_LONG_DESC" VARCHAR2(20 BYTE), 
	"x_CODE_REFERENCE" VARCHAR2(20 BYTE), 
	 CONSTRAINT "x_CODE_PK" PRIMARY KEY ("x_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;