OPTIONS (SKIP=1)
LOAD DATA
INFILE record_type_code_data.csv
BADFILE record_type_code_data.bad
DISCARDFILE record_type_code_data.dsc
INSERT INTO TABLE record_type_code
FIELDS TERMINATED BY ","
(RECORD_TYPE_CODE, RECORD_TYPE_CODE_SHORT_DESC, RECORD_TYPE_CODE_LONG_DESC, RECORD_TYPE_CODE_REFERENCE) 